# Generated by Django 4.0.4 on 2023-07-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('company', models.CharField(max_length=50)),
                ('clientCode', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('assigned_personnel', models.CharField(max_length=50)),
                ('personnelID', models.IntegerField()),
            ],
        ),
    ]
